site_name: DomainSale
pages:
        - Home: index.md
        - Process: process.md
        - Contract: contract.md
        - Events: events.md
        - Clients:
          - Command-line interface: clients/cli.md
        - Help: help.md
